<?php
require_once __DIR__ . '/../includes/db.php'; require_once __DIR__ . '/../includes/functions.php'; start_secure_session();
if (is_admin()) { header('Location: dashboard.php'); exit; }
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  if (!verify_csrf()) { $error = 'La sesión expiró. Volvé a intentar.'; }
  else { $email = trim((string)filter_input(INPUT_POST, 'email', FILTER_SANITIZE_EMAIL)); $password = (string)($_POST['password'] ?? ''); try { $result = supabase_request('GET', 'admins?select=id,name,password_hash&email=eq.' . rawurlencode($email) . '&limit=1'); $admin = $result['data'][0] ?? null; if ($admin && password_verify($password, $admin['password_hash'])) { session_regenerate_id(true); $_SESSION['admin_id'] = $admin['id']; $_SESSION['admin_name'] = $admin['name']; header('Location: dashboard.php'); exit; } $error = 'Correo o contraseña incorrectos.'; } catch (Throwable $e) { $error = 'No se pudo conectar con la base de datos en la nube. Revisá la configuración.'; } }
}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Acceso administrativo | GL Logística</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="../assets/css/admin.css"></head><body class="login-page"><main class="login-card"><a href="../index.php" class="login-logo"><img src="../assets/img/logo-original.png" alt="GL Logística Aduanera"></a><h1>Bienvenido</h1><p>Ingresá al panel de administración.</p><?php if ($error): ?><div class="alert error"><?= e($error) ?></div><?php endif; ?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" required autocomplete="email"><label for="password">Contraseña</label><input id="password" name="password" type="password" required autocomplete="current-password"><button type="submit">Iniciar sesión</button></form><a class="back-link" href="../index.php">← Volver al sitio</a></main></body></html>
