-- Ejecutar este archivo completo en Supabase > SQL Editor > New query.
-- La web se conecta desde PHP mediante la clave secret; las tablas siguen
-- protegidas contra cualquier acceso directo público.

create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(190) not null unique,
  password_hash varchar(255) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  company varchar(150),
  email varchar(190) not null,
  phone varchar(60) not null,
  service varchar(150),
  message text not null,
  status text not null default 'new' check (status in ('new', 'read')),
  created_at timestamptz not null default now()
);

create index if not exists contact_messages_status_idx on public.contact_messages (status);
create index if not exists contact_messages_created_at_idx on public.contact_messages (created_at desc);

alter table public.admins enable row level security;
alter table public.contact_messages enable row level security;

-- No exponer mensajes ni administradores al navegador. El servidor PHP usa
-- la clave secret, que tiene acceso privado y evita estas políticas.
revoke all on table public.admins from anon, authenticated;
revoke all on table public.contact_messages from anon, authenticated;
grant all on table public.admins to service_role;
grant all on table public.contact_messages to service_role;
grant usage, select on all sequences in schema public to service_role;
